import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Satisfy } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "@/components/home-components/SmoothScrollWrapper";
import { CustomizerContextProvider } from "@/context/CustomizerContext";
import './globals.css'
import { useSmoothScroll } from "@/hooks/smoothScrooling";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400","500","600","700",],
});

const satisfy = Satisfy({
  subsets: ["latin"],
  variable: "--font-satisfy",
  weight: ["400"], // Satisfy usually has one weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // useSmoothScroll()
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${satisfy.variable} antialiased`}
      >
        {/* <SmoothScrollWrapper> */}
          <CustomizerContextProvider>
            <ToastContainer position="top-right" />
            
            {children}
          </CustomizerContextProvider>,
        {/* </SmoothScrollWrapper> */}
      </body>
    </html>
  );
}
